### ISSUE TITLE
[BUG] Switching to a scene without Collapse/Hide doesn't uncollapse sidebar and show all gui elements

### ISSUE THREAD

**Issue by yjeroen** [CDeenen/LockView#68] opened 2022-01-25 06:34 UTC
**Setup**
OS: Windows
Browser: Chrome
Module version: 1.5.0
Foundry version: 9.242
Gaming system & version: Symbaroum
Any other modules enabled: yes

**Describe the bug**
When switching from a scene with collapsed gui,
![image](https://user-images.githubusercontent.com/1303988/150923414-d1a2ae52-5a10-43db-90de-2ab2e05b91fd.png)

To a scene without a collapsed gui,
![image](https://user-images.githubusercontent.com/1303988/150923481-6b1f06d9-2383-4381-923c-182fe606e511.png)

Does not unhide/uncollapse all gui items:
![image](https://user-images.githubusercontent.com/1303988/150923543-06d251f0-eb5f-4ecd-bd60-ec1e2240fafa.png)

The following was expected (and only shown after F5 refresh page when the 2nd scene is active):
![image](https://user-images.githubusercontent.com/1303988/150923624-b64c96a8-e994-4d9e-ae9c-1b458fda1469.png)

**Console Log**
No console errors.

**Additional context**

**Comment by CDeenen** [comment] 2022-03-02 23:28
The function was never meant to uncollapse the sidebar when a scene is loaded with 'collapse sidebar' unchecked, so that part functions as intended.
However, some of the ui elements not showing is unintended. A temporary fix (until it is fixed in an update) is to uncheck 'Hide UI Elements' but uncheck all the options in the second scene

**Comment by CDeenen** [comment] 2022-03-22 12:38
This issue should be fixed in v1.5.1.
Please note that it still does not uncollapse the sidebar, since it's not meant to do that.

**Closed by CDeenen** 2022-03-22 12:38 UTC
Labels: bug
