### ISSUE TITLE
Lock View stopped working (Foundry 0.8.9)

### ISSUE THREAD

**Issue by JavaShipped** [CDeenen/LockView#62] opened 2021-11-28 15:29 UTC
I've been using this module successfully for a while now, since 0.7.x and its amazing (thank you!)

My game was on a little hiatus. I updated my foundry from 0.8.3/4 to the current version (0.8.9) and I can't seem to get anything to actually "lock view". Players can still pan and zoom as they please. As far as I can see no other mods are having issues. 

In the log, everytime I save a new config I get the output: 

`You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document`

I'm not sure thats a relevant error, as it seems to throw on other modules as well, so I'm not sure its specific to lock view. But maybe the root of the problem?

Troubleshooting steps already taken:
I am troubleshooting this using a private browser (firefox) and logging in using the local invitation link.

1. Tried disabling all mods except lock view - Unsuccessful
2. Created a new scene and manually input configs - Unsuccessful
3. Created new players each with different permissions - Unsuccessful
4. Tried creating a new world with only lock view as an enabled mod and start the "Example for a static landing page or full screen 'splashscreen':" as directed in the readme - Unsuccessful
5. Reinstalled 0.8.9 to see if maybe I messed something up - Unsuccessful
6. (Edit) uninstalled Lock View -> Reinstalled. - Unsuccessful

**Comment by krusty4president** [comment] 2021-11-30 13:45
Same for me with 0.8.9. Please fix. Thanks

**Comment by CDeenen** [comment] 2021-11-30 16:01
Assuming everything has been configured correctly (the thing most people miss is setting up the User Configuration in the module settings), this seems to be a duplicate of #57. For this reason I'm going to close this issue. If you believe this is a separate issue, it can be reopened.

**Closed by CDeenen** 2021-11-30 16:01 UTC
