### ISSUE TITLE
[BUG] Something broke LockView - was working fine, but now players have full control

### ISSUE THREAD

**Issue by TinyPirate** [CDeenen/LockView#57] opened 2021-09-07 13:53 UTC
**Setup**
 - OS: Windows
 - Browser: Chrome
 - Module version: Latest as at 8 Sept
 - Foundry version: Latest as at 8 sept
 - Gaming system & version: FFG Star Wars
 - Any other modules enabled: Yes

**Describe the bug**
LockView had full control and was working very reliably at preventing pan or scroll or zoom and on "automatic fit inside" so players (and me) couldn't move the scene around at all. However, it no longer works. I've installed "Ambient Doors" and run some basic macros from here: https://github.com/halfwalk/halfwalk-fvtt-macros/tree/main/SW-FFG - but done nothing else and I don't know why it's being bad. I've tried turning off doors and reloading the foundry - no change.

**Screenshots**

**Console Log**
I changed a scene and checked the F12 and the only error is this, which doesn't seem related.
`VM1354:18 Uncaught (in promise) TypeError: Cannot read property 'data' of null
[Detected 2 packages: launchmacro, lib-wrapper]
    at eval (eval at _executeScript (foundry.js:14802), <anonymous>:18:16)
    at Macro.eval (eval at _executeScript (foundry.js:14802), <anonymous>:20:7)
    at Macro._executeScript (foundry.js:14804)
    at Macro.execute (foundry.js:14765)
    at hookmacro.js:188
    at Function._call (eval at <anonymous> (listeners.js:99), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at CombatTracker._render (foundry.js:2104)
    at async CombatTracker._render (foundry.js:23500)`

**Additional context**

**Comment by CDeenen** [comment] 2021-09-07 18:24
I can't seem to reproduce this issue.
You're right about the console error, they don't appear to be related. Do you also get that error when you disable Lock View?
Also, please check that 'Control' is (still) enabled for the players in the 'User Configuration' screen in the module settings.
Otherwise, could you create a new world and check if the issue persists?

**Comment by TinyPirate** [comment] 2021-09-08 03:26
I've created new test worlds, one with the Star Wars system, one with Call of Cthulhu. With both systems I get no errors on load, and no errors on enabling lock view. In both systems I don't get LockView working. In both worlds I've got "gamemaster" ticked under "control" - very strange.

**Comment by CDeenen** [comment] 2021-09-08 06:25
Very strange indeed...
Could you try reinstalling the module? Maybe something got corrupted during the last update.

**Comment by TinyPirate** [comment] 2021-09-08 12:06
Uninstalling and reinstalling didn't do anything. I tried creating a new scene to test if that would make a difference after uninstalling or reinstalling. Interestingly, when I uninstalled and reinstalled - on the reinstall (despite closing Foundry and opening it without LockView, and then closing, opening, and reinstalling), LockView was automatically ticked in my modules and the scenes remembered their lock view settings. 
LockView still has some control over the scene. If I've dragged a scene all over, toggling on, or toggling off and on the "bounding box" button in the LockView side menu returns the scene to how it should be (but only the GM has this button, bummer). The scene is then "Locked" for me, the GM, until I click on any other left menu item (eg, changing to the tile view) or until I click on the right-most menu panel. Either of those things means I can go back to mouse-wheeling and so-on to control the view.

**Comment by FGiorgi** [comment] 2021-09-08 16:16
Hi!
I'm having the same exact issue.
Histing through the forge, dnd5e systen, everytjing updated as of today. No errors in the console.

**Comment by Grygon** [comment] 2021-09-11 18:48
Can also replicate. dnd5e, self-hosted, everything up to date. No relevant errors.

**Comment by Grygon** [comment] 2021-09-11 19:06
Looks like the variables (lockZoom etc) aren't getting set properly--is the expectation that they get carried over from a different layer of the stack or should they be getting set here?
![image](https://user-images.githubusercontent.com/647846/132958743-840da3ea-bfe0-4d99-b2ca-ebcdb1b83e27.png)

**Comment by CDeenen** [comment] 2021-09-13 16:21
> 
> 
> Looks like the variables (lockZoom etc) aren't getting set properly--is the expectation that they get carried over from a different layer of the stack or should they be getting set here?

They are global variables that get updated whenever getFlags() is called.

However, I just noticed that if 'Control' is enabled for the GM, I am able to reproduce some issues. Could you guys confirm that the issue goes away when you disable it for the GM?
I will be looking for a fix, but it would be good to know if this solves it, so I know I don't have to look further for other problems.

**Comment by TinyPirate** [comment] 2021-09-15 10:34
Nope. Created a new world. Two users (GM and Test). Turned on lockview. Turned on lockview only for the test user and neither GM nor test are constrained. clicking on left menu items as either GM or test (with control ticked) resets the view to the "lock" setting but - as per - you can still scroll, pan, etc.

**Comment by FGiorgi** [comment] 2021-09-21 06:42
Same here. Tuning off control doesn´t change the behaviour

**Comment by KammaKhazi** [comment] 2021-09-22 22:17
Also having this problem recently running on the forge. Used to work fine, but I noticed recently the locking functions do nothing now sadly.

**Comment by Jmwhite45** [comment] 2021-10-30 00:17
Having the same issue. Here is my setup.
Windows 10
Chrome
Foundry 0.8.8
Pathfinder 1 0.79.1
hosted on the forge

I also tried turning off the GM control and nothing happened

I also run a different server and it works over there. There we are running
Foundry 0.8.9
D&D 5e 1.5.3
Hosted on Molten Hosting

Looking at this could it be something with the forge?

**Comment by TinyPirate** [comment] 2021-10-31 09:49
Self-hosted here and the problem persists.

**Comment by CDeenen** [comment] 2021-11-30 15:58
A quick update on this bug. I have tried multiple things to reproduce this, but up until now without succes. This makes it very difficult to debug, since I don't really have a starting point from where I could look for the bug. I have been quite busy over the last few months, but I can hopefully spend some time to really dig into the code soon.

**Comment by CDeenen** [comment] 2021-12-30 23:39
I just updated Lock View. Could someone test to see if this issue persists?
If you do, please let me know on what Foundry version you are.

**Comment by KammaKhazi** [comment] 2021-12-31 19:33
@CDeenen hi, thanks for looking into this and happy new year! Sorry for delay in replying, for me hosting on Forge at least I'm sorry to say the problems persist. When i selected auto scaling in scene options I noticed it didn't scale the background like it used to. Then upon logging in on a player account they still had full access to pan and zoom (and again image not auto scaled).
Here is a screen shot of my Lock View scene config settings:-

![LockView](https://user-images.githubusercontent.com/81476445/147837098-e615ebfe-ecf7-4f46-8bff-59a0e5d6a2fb.jpg)

**Comment by gendokun** [comment] 2022-01-04 19:31
Same for me like above, but i am on Foundry 9... Could this be the issue?

**Comment by yjeroen** [comment] 2022-01-06 19:51
Same issue, v9

**Comment by CDeenen** [comment] 2022-01-06 23:37
Thanks for the feedback, I'll give it another try

**Comment by bbollig** [comment] 2022-01-08 21:31
Same issue, I am on 8.9. My game is hosted on Forge and they haven't released v9 yet so I don't believe my issue is related to that. Freshly installed today. PF2e is my game system. I've had intermittent success with getting it work by toggling settings back and forth but there doesn't seem to be any rhyme or reason to it. At one point, captured in the screenshot below, when I removed Control permission from the Game Master and then gave Control permission to my test player account (Brian, in the screenshot) then it was behaving as you would expect. As the Game Master, logged in on Chrome, I was able to pan and zoom a scene where I had those settings disabled and when I flipped over to Firefox for my test player account, I was unable to pan and zoom there as expected. But I have since managed to break that as well. I believe maybe somehow somewhere these permissions are getting negated and overwritten perhaps...
![image](https://user-images.githubusercontent.com/17416030/148660206-6dd3e133-c969-4019-846d-69d674d18e88.png)

**Comment by CDeenen** [comment] 2022-01-08 21:44
That's useful feedback, thanks.
Would you mind enabling control for the 'Trusted Player' role, right below the user-specific settings? If it's an issue where the user settings are overwritten or somehow ignored, I'd expect that the problem does not occur with that enabled.

**Comment by bbollig** [comment] 2022-01-10 22:32
Hey, good catch! It seems like that does have something to do with it.

These are my current permission settings and my test player currently cannot pan or zoom on the scene.

![image](https://user-images.githubusercontent.com/17416030/148849494-35c80cdd-8ed1-4d94-80c4-345b7c0d8bfe.png)

**Comment by CDeenen** [comment] 2022-01-10 23:09
> Hey, good catch! It seems like that does have something to do with it.
> 
> These are my current permission settings and my test player currently cannot pan or zoom on the scene but my GM account can.
> 

Great, that narrows it down. And this should be a workaround that'll work in most cases, at least until a proper fix has been found.

Would you mind trying the following:
-Launch Foundry as one of the users, disable the override in the user config and make sure that the pan and/or zoom locks don't work (I'd like the following steps to be taken when the module isn't working properly)
-Open the console (press F12, make sure you're in the console tab)
-At the bottom you can enter a command, please enter the following: `game.userId`
-Then enter: `game.settings.get("LockView","userSettings")`. It'll probably return something like `Array(2) [ {...}, {...} ]` in which case you can press the arrow to expand it

Please let me know what the console returns. It should look something like this:
![image](https://user-images.githubusercontent.com/68693756/148852621-f6b3e188-0ab1-480b-8b37-4b49293300d8.png)

**Comment by bbollig** [comment] 2022-01-10 23:41
![image](https://user-images.githubusercontent.com/17416030/148856564-95a680aa-5086-4e10-9458-74ec3de39164.png)
![image](https://user-images.githubusercontent.com/17416030/148856602-820f14db-f58a-4287-a281-a8a387edb24c.png)

**Comment by CDeenen** [comment] 2022-01-10 23:47
> This is my player console

Sorry, I should've clarified a bit better that you should enable 'Control' for the player you try it on. So put it in a state where it should work (zoom lock and pan lock enabled on that scene, and Control enabled for the player), but it doesn't work due to this bug.

**Comment by bbollig** [comment] 2022-01-11 00:19
Well, it looks like I am going to have to eat some crow here... I mistook the "Control" setting to mean who is allowed control of the scene, i.e. who is allowed to pan and zoom. But I'm realizing now that that setting means who the module controls the view for. So in my head the meaning of Control being enabled was opposite. 

As it is now, I have Control enabled for all my players and I've logged in as each and they cannot pan or zoom, as is my intention on the scene currently activated.

I could have sworn that the case on Saturday was regardless of the state of that setting, players were allowed zoom and pan... but today I can't reproduce the behavior I thought I was experiencing.

Thanks for your attention and very sorry to have wasted your time on this.

**Comment by KammaKhazi** [comment] 2022-01-11 00:34
You are not alone it seems. Apologies I too misunderstood that permission setting. So you tick it to allow the module to control there view and not to allow the user too. Just checked and with my users ticked it now locks them as desired.

**Comment by CDeenen** [comment] 2022-01-11 03:21
Haha, no worries, I can see how it can be confusing, I'll make it a bit clearer in a next update.
I'll wait a bit for other people to respond, in case it is still not working for them, otherwise I'll close this issue.

**Comment by bbollig** [comment] 2022-01-11 04:21
Hey guess what, I managed to break it again. When it was working, Autoscale was set to Off. I started playing around with the scene settings and set it to Automatic Fit (outside) and then when I swapped back to the player, they were again able to pan and zoom. Changing Autoscale to anything besides Off breaks the lock.

This is a screenshot of the console output you were asking for earlier:
![image](https://user-images.githubusercontent.com/17416030/148880336-b727b025-ed9f-40f4-b7bd-6d3e5f766a1e.png)

And to prove that I am not crazy...
![image](https://user-images.githubusercontent.com/17416030/148880433-6581b8da-62b8-4acf-94a3-b7a7ea42761b.png)
![image](https://user-images.githubusercontent.com/17416030/148880491-c45e5ea4-ce3c-4328-b1b1-29de0d8ca23c.png)

**Comment by yjeroen** [comment] 2022-01-11 10:43
I just re-enabled the module to retry as well, here's my current config:

![image](https://user-images.githubusercontent.com/1303988/148928229-8be77cce-e986-4c13-826c-93a965f64f87.png)

![image](https://user-images.githubusercontent.com/1303988/148928288-962c0035-5dbe-4725-be0e-1307e8bf8e7d.png)

But I can still zoom/pan on the scene.

**Comment by CDeenen** [comment] 2022-01-11 11:58
@bbollig thanks for the console log, that all seems to be fine, so I don't think it's a problem with the settings
@yjeroen would you mind setting autoscale to off? That worked for @bbollig, if that also works for you. And what system do you use, and how is your Foundry server hosted (forge, RPi, using the Foundry app, etc?).

And would both of you mind disabling all other modules. Someone has reported before that this didn't help, but I want to double check.

**Comment by yjeroen** [comment] 2022-01-11 13:16
![image](https://user-images.githubusercontent.com/1303988/148949001-6a4dd601-2506-4645-b3e6-4cfb78ffa560.png)

That works! Now I can't zoom/pan.

**Comment by lambrijer** [comment] 2022-01-14 13:59
I was having similar issues as well, here are my findings (OS X, Foundry VTT 9.0 app and Chrome):

By setting the Autoscale function to "off" LockView works as intended. No need to override single user permissions like bbollig. Setting it to anything else gives the user the option to pan/zoom again.

I also agree that "Control" is a confusing toggle, as I assumed this allowed those players control over the scene, and not that LockView can control it for them. "Apply to" or something seems more clear to me.

**Comment by CDeenen** [comment] 2022-03-22 12:40
I might've found the solution to this. Could someone please check the latest version (v1.5.1)?

**Comment by tmilktoast** [comment] 2022-03-22 22:29
Hey there. Good news. I happened to stumble upon this just now because I was experiencing the same issue. I updated to 1.5.2 and it still didn't work. So uninstalled and then reinstalled it and it is now working.

**Comment by TinyPirate** [comment] 2022-03-23 05:50
OMG I THINK YOU HAVE FIXED IT! THANK YOU!

**Comment by CDeenen** [comment] 2022-03-23 06:08
Happy to hear that, and thanks for your patience.
And @TinyPirate, thanks for the coffee :D

I'll leave this issue open for a few extra days, just in case it didn't fix it for someone.

**Closed** 2022-08-28 23:01 UTC
Labels: bug
