### ISSUE TITLE
[BUG] Blank screen on initial world load

### ISSUE THREAD

**Issue by andy-jones** [CDeenen/LockView#85] opened 2022-09-13 08:32 UTC
**Setup**
 - OS: Mac OS Monterey 12.5.1
 - Browser: Chrome and Foundry standalone application
 - Module version: 1.5.4
 - Foundry version: Foundry Version 10 - Build 285
 - Gaming system & version: Call of Cthulhu 7e (unofficial), D&D5.E, MoSh
 - Any other modules enabled: no

**Describe the bug**
When the world first loads, the scene does not appear, it is just black. If I switch to another scene and then back again, it appears. If I resize the browser window, the locked view resets.

**Screenshots**

**Console Log**
foundry.js:23369 Uncaught TypeError: this.updateBlur is not a function
[Detected 1 package: LockView]
    at Object.set (foundry.js:23369)
    at Canvas.set blurDistance [as blurDistance] (foundry.js:24622)
    at Canvas.pan_OverrideHigherRes (modules/LockView/src/overrides.js:158)
    at Canvas._onResize (foundry.js:24506)
    at _onWindowResize (foundry.js:8790)

**Additional context**

**Comment by CDeenen** [comment] 2022-09-14 00:35
This is a duplicate of #83, and should be fixed in the latest update

**Closed by CDeenen** 2022-09-14 00:35 UTC
Labels: bug

**Comment by andy-jones** [comment] 2022-09-14 07:05
Brilliant. Thanks, I really appreciate the hard work you put into these modules.
