### ISSUE TITLE
[BUG] [W] libWrapper: Potential conflict detected between module Lock View and module Zoom/Pan Options. Detected non-libWrapper wrapping of 'Canvas.prototype._onDragCanvasPan' by module LockView. This will potentially lead to conflicts.

### ISSUE THREAD

**Issue by jocolamarco** [CDeenen/LockView#71] opened 2022-02-26 21:08 UTC
**Setup**
 - OS: [e.g. windows] windows
 - Browser: [e.g. chrome, safari, Foundry app] chrome 97
 - Module version: [e.g. 1.2.5] 1.5.0
 - Foundry version: [e.g. 0.8.6] v9 249
 - Gaming system & version: [e.g. dnd5e 1.3.3] pf2e 3.5.5
 - Any other modules enabled: [yes/no] yes

**Describe the bug**
[W] libWrapper: Potential conflict detected between module Lock View and module Zoom/Pan Options.
Detected non-libWrapper wrapping of 'Canvas.prototype._onDragCanvasPan' by module LockView. This will potentially lead to conflicts.

**Screenshots**
![image](https://user-images.githubusercontent.com/45291719/155859072-6e2f0550-e86b-46c4-acc8-6cb5828da3b7.png)

**Console Log**
above

**Additional context**
above

**Comment by CDeenen** [comment] 2022-03-02 23:13
This looks like a duplicate of #46

**Closed by CDeenen** 2022-03-02 23:13 UTC
Labels: bug
